version: "3"

services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./app:/var/www/html
      - ./logs:/var/log/nginx
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8093:80"

  calc:
    container_name: calc
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/html

volumes:
  calc: